"""add raw responses table

Revision ID: ec47af133e82
Revises: 002_add_geocoding_cache
Create Date: 2026-09-03 09:28:58.815051
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ec47af133e82'
down_revision: str | None = "002_gold_air_quality"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_responses',
    sa.Column('raw_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.Text(), nullable=False),
    sa.Column("pipeline_run_id", sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()'),),
    sa.CheckConstraint('window_end > window_start', name='ck_raw_responses_valid_window'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.city_id'], ),
    sa.ForeignKeyConstraint(["pipeline_run_id"], ["pipeline_runs.id"],),
    sa.PrimaryKeyConstraint('raw_id'),
    sa.UniqueConstraint('city_id',  'pipeline_run_id', 'window_start', 'window_end', name='uq_raw_responses_city_run_window')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_responses')
    # ### end Alembic commands ###
